version: "3.8"

services: 
    backend:
          image: ubuntu
          container_name: "rest_api"
          restart: on-failure
          build: 
            context: "./backend"
            dockerfile: Dockerfile
          ports:
            - 8000:8080
          volumes:
            - ./backend/api:/usr/src/app/
          depends_on: 
            - db
          networks: 
            - fullstack
    db:
          image: mysql:5.7.22
          container_name: "database"
          restart: always
          environment: 
               MYSQL_DATABASE: admin
               MYSQL_USER: root
               MYSQL_PASSWORD: root
               MYSQL_ROOT_PASSWORD: "admin"
          volumes: 
              - ./backend/.dbdata:/var/lib/mysql
              - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
          ports: 
              - 33066:3306
          networks: 
              - fullstack
    # frontend:
    #       image: node
    #       container_name: "frontend"
    #       stdin_open: true
    #       environment:
    #         - CHOKIDAR_USEPOLLING=true
    #       build:
    #         dockerfile: Dockerfile
    #         context: ./frontend
    #       depends_on:
    #         - backend
    #       restart: always
    #       volumes:
    #         - /app/node_modules
    #         - ./frontend:/app
    #       networks: 
    #           - fullstack

volumes:
  backend: 
  api:

networks: 
  fullstack:
    driver: bridge